# Std Lib
require 'securerandom'

# 3rd party gems
require 'rack/session'
require 'rack/test'
require 'json'
require 'omniauth'
require 'byebug' if ENV['DEBUG'] == 'true'
# This does not require "simplecov",
#   because that has a side-effect of running `.simplecov`
require 'kettle-soup-cover'

OmniAuth.config.logger = Logger.new('/dev/null')
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  
  include Rack::Test::Methods

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

# Last thing before loading this library, load simplecov:
require 'simplecov' if Kettle::Soup::Cover::DO_COV

require 'omniauth/jwt'
